// Generated by NClassify.Generator, Version=1.0
#pragma warning disable 1591, 0612, 3021
#region Designer generated code
namespace NClassify.Generator
{
    [global::System.Xml.Serialization.XmlType("asdf")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NClassify.Generator", "1.0")]
    public enum Asdf
    {
        /// <summary>
        /// asdf = 1
        /// </summary>
        [global::System.Xml.Serialization.XmlEnum("asdf")] Asdf = 1,
        /// <summary>
        /// fdsa = 2
        /// </summary>
        [global::System.Xml.Serialization.XmlEnum("fdsa")] Fdsa = 2,
        /// <summary>
        /// sdfa = 3
        /// </summary>
        [global::System.Xml.Serialization.XmlEnum("sdfa")] Sdfa = 3,
    }
    [global::System.Xml.Serialization.XmlType("callback_id")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NClassify.Generator", "1.0")]
    public partial struct CallbackId : System.IEquatable<CallbackId>, System.IComparable<CallbackId>
    {
        private bool __has_value;
        private ulong __value;
        [global::System.CLSCompliant(false)]
        public CallbackId(ulong value) : this()
        {
            this.Value = value;
        }
        [global::System.Xml.Serialization.XmlElement("hasValue")]
        public bool HasValue
        {
            get
            {
                return __has_value;
            }
        }
        private bool SetValue(ulong value)
        {
            __value = value;
            __has_value = true;
            return true;
        }
        [global::System.Xml.Serialization.XmlElement("value")]
        public ulong Value
        {
            get
            {
                if (!__has_value) throw new global::System.InvalidOperationException();
                return __value;
            }
            private set
            {
                if (!SetValue(value)) throw new global::System.ArgumentOutOfRangeException("Value");
            }
        }
        public override string ToString()
        {
            return __has_value ? __value.ToString() : null;
        }
        public override int GetHashCode()
        {
            return __has_value ? __value.GetHashCode() : 0;
        }
        public override bool Equals(object obj)
        {
            return obj is CallbackId ? Equals((CallbackId)obj) : base.Equals(obj);
        }
        public bool Equals(CallbackId other)
        {
            return __has_value && other.__has_value ? __value.Equals(other.__value) : __has_value == other.__has_value;
        }
        public int CompareTo(CallbackId other)
        {
            return __has_value && other.__has_value ? __value.CompareTo(other.__value) : __has_value ? 1 : __has_value ? -1 : 0;
        }
        [global::System.CLSCompliant(false)]
        public static explicit operator CallbackId(ulong value)
        {
            return new CallbackId(value);
        }
        [global::System.CLSCompliant(false)]
        public static explicit operator ulong(CallbackId value)
        {
            return value.Value;
        }
        public static bool operator ==(CallbackId x, CallbackId y)
        {
            return x.Equals(y);
        }
        public static bool operator !=(CallbackId x, CallbackId y)
        {
            return !x.Equals(y);
        }
    }
    [global::System.Xml.Serialization.XmlType("event_type")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NClassify.Generator", "1.0")]
    public partial struct EventType : System.IEquatable<EventType>, System.IComparable<EventType>
    {
        private bool __has_value;
        private string __value;
        public EventType(string value) : this()
        {
            this.Value = value;
        }
        [global::System.Xml.Serialization.XmlElement("hasValue")]
        public bool HasValue
        {
            get
            {
                return __has_value;
            }
        }
        private bool SetValue(string value)
        {
            if (null == value) return false;
            __value = value;
            __has_value = true;
            return true;
        }
        [global::System.Xml.Serialization.XmlElement("value")]
        public string Value
        {
            get
            {
                if (!__has_value) throw new global::System.InvalidOperationException();
                return __value;
            }
            private set
            {
                if (!SetValue(value)) throw new global::System.ArgumentOutOfRangeException("Value");
            }
        }
        public override string ToString()
        {
            return __has_value ? __value.ToString() : null;
        }
        public override int GetHashCode()
        {
            return __has_value ? __value.GetHashCode() : 0;
        }
        public override bool Equals(object obj)
        {
            return obj is EventType ? Equals((EventType)obj) : base.Equals(obj);
        }
        public bool Equals(EventType other)
        {
            return __has_value && other.__has_value ? __value.Equals(other.__value) : __has_value == other.__has_value;
        }
        public int CompareTo(EventType other)
        {
            return __has_value && other.__has_value ? __value.CompareTo(other.__value) : __has_value ? 1 : __has_value ? -1 : 0;
        }
        public static explicit operator EventType(string value)
        {
            return new EventType(value);
        }
        public static explicit operator string(EventType value)
        {
            return value.Value;
        }
        public static bool operator ==(EventType x, EventType y)
        {
            return x.Equals(y);
        }
        public static bool operator !=(EventType x, EventType y)
        {
            return !x.Equals(y);
        }
    }
    [global::System.Xml.Serialization.XmlType("Callback")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NClassify.Generator", "1.0")]
    public partial class Callback
    {
        private bool __has_callbackId;
        private ulong __callbackId;
        private bool __has_uri;
        private global::System.Uri __uri;
        private bool __has_event;
        private string __event;
        private bool __has_verified;
        private bool __verified;
        [global::System.Xml.Serialization.XmlElement("hasCallbackId")]
        public bool HasCallbackId
        {
            get
            {
                return __has_callbackId;
            }
            set
            {
                if (value) throw new global::System.InvalidOperationException();
                __callbackId = 0ul;
                __has_callbackId = false;
            }
        }
        private bool SetCallbackId(ulong value)
        {
            __callbackId = value;
            __has_callbackId = true;
            return true;
        }
        [global::System.Xml.Serialization.XmlElement("callback_id")]
        public global::NClassify.Generator.CallbackId CallbackId
        {
            get
            {
                return (global::NClassify.Generator.CallbackId)__callbackId;
            }
            set
            {
                if (!SetCallbackId((ulong)value)) throw new global::System.ArgumentOutOfRangeException("CallbackId");
            }
        }
        [global::System.Xml.Serialization.XmlElement("hasUri")]
        public bool HasUri
        {
            get
            {
                return __has_uri;
            }
            set
            {
                if (value) throw new global::System.InvalidOperationException();
                __uri = default(global::System.Uri);
                __has_uri = false;
            }
        }
        private bool SetUri(global::System.Uri value)
        {
            __uri = value;
            __has_uri = true;
            return true;
        }
        [global::System.Xml.Serialization.XmlElement("uri")]
        public global::System.Uri Uri
        {
            get
            {
                return __uri;
            }
            set
            {
                if (!SetUri(value)) throw new global::System.ArgumentOutOfRangeException("Uri");
            }
        }
        [global::System.Xml.Serialization.XmlElement("hasEvent")]
        public bool HasEvent
        {
            get
            {
                return __has_event;
            }
            set
            {
                if (value) throw new global::System.InvalidOperationException();
                __event = "";
                __has_event = false;
            }
        }
        private bool SetEvent(string value)
        {
            __event = value;
            __has_event = true;
            return true;
        }
        [global::System.Xml.Serialization.XmlElement("event")]
        public global::NClassify.Generator.EventType Event
        {
            get
            {
                return (global::NClassify.Generator.EventType)__event;
            }
            set
            {
                if (!SetEvent((string)value)) throw new global::System.ArgumentOutOfRangeException("Event");
            }
        }
        [global::System.Xml.Serialization.XmlElement("hasVerified")]
        public bool HasVerified
        {
            get
            {
                return __has_verified;
            }
            set
            {
                if (value) throw new global::System.InvalidOperationException();
                __verified = false;
                __has_verified = false;
            }
        }
        private bool SetVerified(bool value)
        {
            __verified = value;
            __has_verified = true;
            return true;
        }
        [global::System.Xml.Serialization.XmlElement("verified")]
        public bool Verified
        {
            get
            {
                return __verified;
            }
            set
            {
                if (!SetVerified(value)) throw new global::System.ArgumentOutOfRangeException("Verified");
            }
        }
    }
    [global::System.Xml.Serialization.XmlType("CallbackRequest")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NClassify.Generator", "1.0")]
    public partial class CallbackRequest
    {
        private bool __has_callback;
        private global::NClassify.Generator.Callback __callback;
        [global::System.Xml.Serialization.XmlElement("hasCallback")]
        public bool HasCallback
        {
            get
            {
                return __has_callback;
            }
            set
            {
                if (value) throw new global::System.InvalidOperationException();
                __callback = new global::NClassify.Generator.Callback();
                __has_callback = false;
            }
        }
        private bool SetCallback(global::NClassify.Generator.Callback value)
        {
            if (null == value) return false;
            __callback = value;
            __has_callback = true;
            return true;
        }
        [global::System.Xml.Serialization.XmlElement("callback")]
        public global::NClassify.Generator.Callback Callback
        {
            get
            {
                return __callback;
            }
            set
            {
                if (!SetCallback(value)) throw new global::System.ArgumentOutOfRangeException("Callback");
            }
        }
    }
    [global::System.Xml.Serialization.XmlType("CallbackVerify")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NClassify.Generator", "1.0")]
    public partial class CallbackVerify
    {
        private bool __has_callbackId;
        private ulong __callbackId;
        private bool __has_verifier;
        private string __verifier;
        [global::System.Xml.Serialization.XmlElement("hasCallbackId")]
        public bool HasCallbackId
        {
            get
            {
                return __has_callbackId;
            }
            set
            {
                if (value) throw new global::System.InvalidOperationException();
                __callbackId = 0ul;
                __has_callbackId = false;
            }
        }
        private bool SetCallbackId(ulong value)
        {
            __callbackId = value;
            __has_callbackId = true;
            return true;
        }
        [global::System.Xml.Serialization.XmlElement("callback_id")]
        public global::NClassify.Generator.CallbackId CallbackId
        {
            get
            {
                return (global::NClassify.Generator.CallbackId)__callbackId;
            }
            set
            {
                if (!SetCallbackId((ulong)value)) throw new global::System.ArgumentOutOfRangeException("CallbackId");
            }
        }
        [global::System.Xml.Serialization.XmlElement("hasVerifier")]
        public bool HasVerifier
        {
            get
            {
                return __has_verifier;
            }
            set
            {
                if (value) throw new global::System.InvalidOperationException();
                __verifier = "";
                __has_verifier = false;
            }
        }
        private bool SetVerifier(string value)
        {
            if (null == value) return false;
            __verifier = value;
            __has_verifier = true;
            return true;
        }
        [global::System.Xml.Serialization.XmlElement("verifier")]
        public string Verifier
        {
            get
            {
                return __verifier;
            }
            set
            {
                if (!SetVerifier(value)) throw new global::System.ArgumentOutOfRangeException("Verifier");
            }
        }
    }
    [global::System.Xml.Serialization.XmlType("CallbackVerifyRequest")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NClassify.Generator", "1.0")]
    public partial class CallbackVerifyRequest
    {
        private bool __has_callback;
        private global::NClassify.Generator.CallbackVerify __callback;
        [global::System.Xml.Serialization.XmlElement("hasCallback")]
        public bool HasCallback
        {
            get
            {
                return __has_callback;
            }
            set
            {
                if (value) throw new global::System.InvalidOperationException();
                __callback = new global::NClassify.Generator.CallbackVerify();
                __has_callback = false;
            }
        }
        private bool SetCallback(global::NClassify.Generator.CallbackVerify value)
        {
            if (null == value) return false;
            __callback = value;
            __has_callback = true;
            return true;
        }
        [global::System.Xml.Serialization.XmlElement("callback")]
        public global::NClassify.Generator.CallbackVerify Callback
        {
            get
            {
                return __callback;
            }
            set
            {
                if (!SetCallback(value)) throw new global::System.ArgumentOutOfRangeException("Callback");
            }
        }
    }
    [global::System.Xml.Serialization.XmlType("Callbacks")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NClassify.Generator", "1.0")]
    public partial class Callbacks
    {
        private bool __has_callback;
        private global::NClassify.Generator.Callback __callback;
        [global::System.Xml.Serialization.XmlElement("hasCallback")]
        public bool HasCallback
        {
            get
            {
                return __has_callback;
            }
            set
            {
                if (value) throw new global::System.InvalidOperationException();
                __callback = new global::NClassify.Generator.Callback();
                __has_callback = false;
            }
        }
        private bool SetCallback(global::NClassify.Generator.Callback value)
        {
            if (null == value) return false;
            __callback = value;
            __has_callback = true;
            return true;
        }
        [global::System.Xml.Serialization.XmlElement("callback")]
        public global::NClassify.Generator.Callback Callback
        {
            get
            {
                return __callback;
            }
            set
            {
                if (!SetCallback(value)) throw new global::System.ArgumentOutOfRangeException("Callback");
            }
        }
    }
    [global::System.Xml.Serialization.XmlType("CallbacksResponse")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NClassify.Generator", "1.0")]
    public partial class CallbacksResponse
    {
        private bool __has_callbacks;
        private global::NClassify.Generator.Callbacks __callbacks;
        [global::System.Xml.Serialization.XmlElement("hasCallbacks")]
        public bool HasCallbacks
        {
            get
            {
                return __has_callbacks;
            }
            set
            {
                if (value) throw new global::System.InvalidOperationException();
                __callbacks = new global::NClassify.Generator.Callbacks();
                __has_callbacks = false;
            }
        }
        private bool SetCallbacks(global::NClassify.Generator.Callbacks value)
        {
            if (null == value) return false;
            __callbacks = value;
            __has_callbacks = true;
            return true;
        }
        [global::System.Xml.Serialization.XmlElement("callbacks")]
        public global::NClassify.Generator.Callbacks Callbacks
        {
            get
            {
                return __callbacks;
            }
            set
            {
                if (!SetCallbacks(value)) throw new global::System.ArgumentOutOfRangeException("Callbacks");
            }
        }
    }
    [global::System.Xml.Serialization.XmlType("CallbacksRequest")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NClassify.Generator", "1.0")]
    public partial class CallbacksRequest
    {
        private bool __has_page;
        private int __page;
        private bool __has_perPage;
        private int __perPage;
        private bool __has_event;
        private string __event;
        private bool __has_uri;
        private string __uri;
        [global::System.Xml.Serialization.XmlElement("hasPage")]
        public bool HasPage
        {
            get
            {
                return __has_page;
            }
            set
            {
                if (value) throw new global::System.InvalidOperationException();
                __page = 0;
                __has_page = false;
            }
        }
        private bool SetPage(int value)
        {
            __page = value;
            __has_page = true;
            return true;
        }
        [global::System.Xml.Serialization.XmlElement("page")]
        public int Page
        {
            get
            {
                return __page;
            }
            set
            {
                if (!SetPage(value)) throw new global::System.ArgumentOutOfRangeException("Page");
            }
        }
        [global::System.Xml.Serialization.XmlElement("hasPerPage")]
        public bool HasPerPage
        {
            get
            {
                return __has_perPage;
            }
            set
            {
                if (value) throw new global::System.InvalidOperationException();
                __perPage = 0;
                __has_perPage = false;
            }
        }
        private bool SetPerPage(int value)
        {
            __perPage = value;
            __has_perPage = true;
            return true;
        }
        [global::System.Xml.Serialization.XmlElement("per_page")]
        public int PerPage
        {
            get
            {
                return __perPage;
            }
            set
            {
                if (!SetPerPage(value)) throw new global::System.ArgumentOutOfRangeException("PerPage");
            }
        }
        [global::System.Xml.Serialization.XmlElement("hasEvent")]
        public bool HasEvent
        {
            get
            {
                return __has_event;
            }
            set
            {
                if (value) throw new global::System.InvalidOperationException();
                __event = "";
                __has_event = false;
            }
        }
        private bool SetEvent(string value)
        {
            __event = value;
            __has_event = true;
            return true;
        }
        [global::System.Xml.Serialization.XmlElement("event")]
        public global::NClassify.Generator.EventType Event
        {
            get
            {
                return (global::NClassify.Generator.EventType)__event;
            }
            set
            {
                if (!SetEvent((string)value)) throw new global::System.ArgumentOutOfRangeException("Event");
            }
        }
        [global::System.Xml.Serialization.XmlElement("hasUri")]
        public bool HasUri
        {
            get
            {
                return __has_uri;
            }
            set
            {
                if (value) throw new global::System.InvalidOperationException();
                __uri = "";
                __has_uri = false;
            }
        }
        private bool SetUri(string value)
        {
            if (null == value) return false;
            __uri = value;
            __has_uri = true;
            return true;
        }
        [global::System.Xml.Serialization.XmlElement("uri")]
        public string Uri
        {
            get
            {
                return __uri;
            }
            set
            {
                if (!SetUri(value)) throw new global::System.ArgumentOutOfRangeException("Uri");
            }
        }
    }
    [global::System.Xml.Serialization.XmlType("CallbackIdentity")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NClassify.Generator", "1.0")]
    public partial class CallbackIdentity
    {
        private bool __has_callbackId;
        private ulong __callbackId;
        [global::System.Xml.Serialization.XmlElement("hasCallbackId")]
        public bool HasCallbackId
        {
            get
            {
                return __has_callbackId;
            }
            set
            {
                if (value) throw new global::System.InvalidOperationException();
                __callbackId = 0ul;
                __has_callbackId = false;
            }
        }
        private bool SetCallbackId(ulong value)
        {
            __callbackId = value;
            __has_callbackId = true;
            return true;
        }
        [global::System.Xml.Serialization.XmlElement("callback_id")]
        public global::NClassify.Generator.CallbackId CallbackId
        {
            get
            {
                return (global::NClassify.Generator.CallbackId)__callbackId;
            }
            set
            {
                if (!SetCallbackId((ulong)value)) throw new global::System.ArgumentOutOfRangeException("CallbackId");
            }
        }
    }
}
#endregion
