// Generated by NClassify.Generator, Version=1.0
#pragma warning disable 1591, 0612, 3021
#region Designer generated code
namespace NClassify.Generator
{
    /// <summary>
    /// Enumerated type asdf
    /// </summary>
    [global::System.Xml.Serialization.XmlType("asdf")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NClassify.Generator", "1.0")]
    public enum Asdf
    {
        /// <summary>
        /// asdf = 1
        /// </summary>
        [global::System.Xml.Serialization.XmlEnum("asdf")] Asdf = 1,
        /// <summary>
        /// fdsa = 2
        /// </summary>
        [global::System.Xml.Serialization.XmlEnum("fdsa")] Fdsa = 2,
        /// <summary>
        /// sdfa = 3
        /// </summary>
        [global::System.Xml.Serialization.XmlEnum("sdfa")] Sdfa = 3,
    }
    /// <summary>
    /// Value type callback_id
    /// </summary>
    [global::System.Xml.Serialization.XmlType("callback_id")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NClassify.Generator", "1.0")]
    public partial struct CallbackId : System.IEquatable<CallbackId>, System.IComparable<CallbackId>
    {
        [global::System.CLSCompliant(false)]
        public CallbackId(System.UInt64 value) : this()
        {
            this.Value = value;
        }
        private bool __has_value;
        private System.UInt64 __value;
        private bool SetValue(System.UInt64 value)
        {
            if (value < 1) return false;
            __value = value;
            return __has_value = true;
        }
        public bool HasValue
        {
            get
            {
                return __has_value;
            }
            private set
            {
                if (value) throw new System.ArgumentOutOfRangeException("HasValue");
                __has_value = false;
                __value = default(System.UInt64);
            }
        }
        /// <summary>
        /// System.UInt64 value
        /// </summary>
        [global::System.CLSCompliant(false)]
        public System.UInt64 Value
        {
            get
            {
                return (__value);
            }
            private set
            {
                if (!SetValue(value))
                {
                    throw new System.ArgumentOutOfRangeException("Value");
                }
            }
        }
        public override string ToString()
        {
            return __value.ToString();
        }
        public override int GetHashCode()
        {
            return __value.GetHashCode();
        }
        public override bool Equals(object obj)
        {
            return obj is CallbackId ? Equals((CallbackId)obj) : base.Equals(obj);
        }
        public bool Equals(CallbackId other)
        {
            return __value.Equals(other.__value);
        }
        public int CompareTo(CallbackId other)
        {
            return __value.CompareTo(other.__value);
        }
        [global::System.CLSCompliant(false)]
        public static explicit operator CallbackId(System.UInt64 value)
        {
            return new CallbackId(value);
        }
        [global::System.CLSCompliant(false)]
        public static explicit operator System.UInt64(CallbackId value)
        {
            return value.Value;
        }
        public static bool operator ==(CallbackId x, CallbackId y)
        {
            return x.__value.Equals(y.__value);
        }
        public static bool operator !=(CallbackId x, CallbackId y)
        {
            return !x.__value.Equals(y.__value);
        }
    }
    /// <summary>
    /// Value type event_type
    /// </summary>
    [global::System.Xml.Serialization.XmlType("event_type")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NClassify.Generator", "1.0")]
    public partial struct EventType : System.IEquatable<EventType>, System.IComparable<EventType>
    {
        public EventType(System.String value) : this()
        {
            this.Value = value;
        }
        private bool __has_value;
        private System.String __value;
        private bool SetValue(System.String value)
        {
            if (null == value) return false;
            __value = value;
            return __has_value = true;
        }
        public bool HasValue
        {
            get
            {
                return __has_value;
            }
            private set
            {
                if (value) throw new System.ArgumentOutOfRangeException("HasValue");
                __has_value = false;
                __value = default(System.String);
            }
        }
        /// <summary>
        /// System.String value
        /// </summary>
        public System.String Value
        {
            get
            {
                return (__value);
            }
            private set
            {
                if (!SetValue(value))
                {
                    throw new System.ArgumentOutOfRangeException("Value");
                }
            }
        }
        public override string ToString()
        {
            return __value.ToString();
        }
        public override int GetHashCode()
        {
            return __value.GetHashCode();
        }
        public override bool Equals(object obj)
        {
            return obj is EventType ? Equals((EventType)obj) : base.Equals(obj);
        }
        public bool Equals(EventType other)
        {
            return __value.Equals(other.__value);
        }
        public int CompareTo(EventType other)
        {
            return __value.CompareTo(other.__value);
        }
        public static explicit operator EventType(System.String value)
        {
            return new EventType(value);
        }
        public static explicit operator System.String(EventType value)
        {
            return value.Value;
        }
        public static bool operator ==(EventType x, EventType y)
        {
            return x.__value.Equals(y.__value);
        }
        public static bool operator !=(EventType x, EventType y)
        {
            return !x.__value.Equals(y.__value);
        }
    }
    /// <summary>
    /// Value type Callback
    /// </summary>
    [global::System.Xml.Serialization.XmlType("Callback")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NClassify.Generator", "1.0")]
    public partial class Callback
    {
        private bool __has_callbackId;
        private System.UInt64 __callbackId;
        [global::System.CLSCompliant(false)]
        protected bool SetCallbackId(System.UInt64 value)
        {
            __callbackId = value;
            return __has_callbackId = true;
        }
        public bool HasCallbackId
        {
            get
            {
                return __has_callbackId;
            }
            set
            {
                if (value) throw new System.ArgumentOutOfRangeException("HasCallbackId");
                __has_callbackId = false;
                __callbackId = default(System.UInt64);
            }
        }
        /// <summary>
        /// System.UInt64 callback_id
        /// </summary>
        [global::System.CLSCompliant(false)]
        public NClassify.Generator.CallbackId CallbackId
        {
            get
            {
                return new NClassify.Generator.CallbackId(__callbackId);
            }
            set
            {
                if (!SetCallbackId(value.Value))
                {
                    throw new System.ArgumentOutOfRangeException("CallbackId");
                }
            }
        }
        private bool __has_uri;
        private global::System.Uri __uri;
        protected bool SetUri(global::System.Uri value)
        {
            __uri = value;
            return __has_uri = true;
        }
        public bool HasUri
        {
            get
            {
                return __has_uri;
            }
            set
            {
                if (value) throw new System.ArgumentOutOfRangeException("HasUri");
                __has_uri = false;
                __uri = default(global::System.Uri);
            }
        }
        /// <summary>
        /// global::System.Uri uri
        /// </summary>
        public global::System.Uri Uri
        {
            get
            {
                return (__uri);
            }
            set
            {
                if (!SetUri(value))
                {
                    throw new System.ArgumentOutOfRangeException("Uri");
                }
            }
        }
        private bool __has_event;
        private System.String __event;
        protected bool SetEvent(System.String value)
        {
            if (null == value) return false;
            __event = value;
            return __has_event = true;
        }
        public bool HasEvent
        {
            get
            {
                return __has_event;
            }
            set
            {
                if (value) throw new System.ArgumentOutOfRangeException("HasEvent");
                __has_event = false;
                __event = default(System.String);
            }
        }
        /// <summary>
        /// System.String event
        /// </summary>
        public NClassify.Generator.EventType Event
        {
            get
            {
                return new NClassify.Generator.EventType(__event);
            }
            set
            {
                if (!SetEvent(value.Value))
                {
                    throw new System.ArgumentOutOfRangeException("Event");
                }
            }
        }
        private bool __has_verified;
        private System.Boolean __verified;
        protected bool SetVerified(System.Boolean value)
        {
            __verified = value;
            return __has_verified = true;
        }
        public bool HasVerified
        {
            get
            {
                return __has_verified;
            }
            set
            {
                if (value) throw new System.ArgumentOutOfRangeException("HasVerified");
                __has_verified = false;
                __verified = default(System.Boolean);
            }
        }
        /// <summary>
        /// System.Boolean verified
        /// </summary>
        public System.Boolean Verified
        {
            get
            {
                return (__verified);
            }
            set
            {
                if (!SetVerified(value))
                {
                    throw new System.ArgumentOutOfRangeException("Verified");
                }
            }
        }
    }
    /// <summary>
    /// Value type CallbackRequest
    /// </summary>
    [global::System.Xml.Serialization.XmlType("CallbackRequest")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NClassify.Generator", "1.0")]
    public partial class CallbackRequest
    {
        private bool __has_callback;
        private NClassify.Generator.Callback __callback;
        protected bool SetCallback(NClassify.Generator.Callback value)
        {
            if (null == value) return false;
            __callback = value;
            return __has_callback = true;
        }
        public bool HasCallback
        {
            get
            {
                return __has_callback;
            }
            set
            {
                if (value) throw new System.ArgumentOutOfRangeException("HasCallback");
                __has_callback = false;
                __callback = default(NClassify.Generator.Callback);
            }
        }
        /// <summary>
        /// NClassify.Generator.Callback callback
        /// </summary>
        public NClassify.Generator.Callback Callback
        {
            get
            {
                return (__callback);
            }
            set
            {
                if (!SetCallback(value))
                {
                    throw new System.ArgumentOutOfRangeException("Callback");
                }
            }
        }
    }
    /// <summary>
    /// Value type CallbackVerify
    /// </summary>
    [global::System.Xml.Serialization.XmlType("CallbackVerify")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NClassify.Generator", "1.0")]
    public partial class CallbackVerify
    {
        private bool __has_callbackId;
        private System.UInt64 __callbackId;
        [global::System.CLSCompliant(false)]
        protected bool SetCallbackId(System.UInt64 value)
        {
            __callbackId = value;
            return __has_callbackId = true;
        }
        public bool HasCallbackId
        {
            get
            {
                return __has_callbackId;
            }
            set
            {
                if (value) throw new System.ArgumentOutOfRangeException("HasCallbackId");
                __has_callbackId = false;
                __callbackId = default(System.UInt64);
            }
        }
        /// <summary>
        /// System.UInt64 callback_id
        /// </summary>
        [global::System.CLSCompliant(false)]
        public NClassify.Generator.CallbackId CallbackId
        {
            get
            {
                return new NClassify.Generator.CallbackId(__callbackId);
            }
            set
            {
                if (!SetCallbackId(value.Value))
                {
                    throw new System.ArgumentOutOfRangeException("CallbackId");
                }
            }
        }
        private bool __has_verifier;
        private System.String __verifier;
        protected bool SetVerifier(System.String value)
        {
            if (null == value) return false;
            __verifier = value;
            return __has_verifier = true;
        }
        public bool HasVerifier
        {
            get
            {
                return __has_verifier;
            }
            set
            {
                if (value) throw new System.ArgumentOutOfRangeException("HasVerifier");
                __has_verifier = false;
                __verifier = default(System.String);
            }
        }
        /// <summary>
        /// System.String verifier
        /// </summary>
        public System.String Verifier
        {
            get
            {
                return (__verifier);
            }
            set
            {
                if (!SetVerifier(value))
                {
                    throw new System.ArgumentOutOfRangeException("Verifier");
                }
            }
        }
    }
    /// <summary>
    /// Value type CallbackVerifyRequest
    /// </summary>
    [global::System.Xml.Serialization.XmlType("CallbackVerifyRequest")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NClassify.Generator", "1.0")]
    public partial class CallbackVerifyRequest
    {
        private bool __has_callback;
        private NClassify.Generator.CallbackVerify __callback;
        protected bool SetCallback(NClassify.Generator.CallbackVerify value)
        {
            if (null == value) return false;
            __callback = value;
            return __has_callback = true;
        }
        public bool HasCallback
        {
            get
            {
                return __has_callback;
            }
            set
            {
                if (value) throw new System.ArgumentOutOfRangeException("HasCallback");
                __has_callback = false;
                __callback = default(NClassify.Generator.CallbackVerify);
            }
        }
        /// <summary>
        /// NClassify.Generator.CallbackVerify callback
        /// </summary>
        public NClassify.Generator.CallbackVerify Callback
        {
            get
            {
                return (__callback);
            }
            set
            {
                if (!SetCallback(value))
                {
                    throw new System.ArgumentOutOfRangeException("Callback");
                }
            }
        }
    }
    /// <summary>
    /// Value type Callbacks
    /// </summary>
    [global::System.Xml.Serialization.XmlType("Callbacks")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NClassify.Generator", "1.0")]
    public partial class Callbacks
    {
        private bool __has_callback;
        private NClassify.Generator.Callback __callback;
        protected bool SetCallback(NClassify.Generator.Callback value)
        {
            if (null == value) return false;
            __callback = value;
            return __has_callback = true;
        }
        public bool HasCallback
        {
            get
            {
                return __has_callback;
            }
            set
            {
                if (value) throw new System.ArgumentOutOfRangeException("HasCallback");
                __has_callback = false;
                __callback = default(NClassify.Generator.Callback);
            }
        }
        /// <summary>
        /// NClassify.Generator.Callback callback
        /// </summary>
        public NClassify.Generator.Callback Callback
        {
            get
            {
                return (__callback);
            }
            set
            {
                if (!SetCallback(value))
                {
                    throw new System.ArgumentOutOfRangeException("Callback");
                }
            }
        }
    }
    /// <summary>
    /// Value type CallbacksResponse
    /// </summary>
    [global::System.Xml.Serialization.XmlType("CallbacksResponse")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NClassify.Generator", "1.0")]
    public partial class CallbacksResponse
    {
        private bool __has_callbacks;
        private NClassify.Generator.Callbacks __callbacks;
        protected bool SetCallbacks(NClassify.Generator.Callbacks value)
        {
            if (null == value) return false;
            __callbacks = value;
            return __has_callbacks = true;
        }
        public bool HasCallbacks
        {
            get
            {
                return __has_callbacks;
            }
            set
            {
                if (value) throw new System.ArgumentOutOfRangeException("HasCallbacks");
                __has_callbacks = false;
                __callbacks = default(NClassify.Generator.Callbacks);
            }
        }
        /// <summary>
        /// NClassify.Generator.Callbacks callbacks
        /// </summary>
        public NClassify.Generator.Callbacks Callbacks
        {
            get
            {
                return (__callbacks);
            }
            set
            {
                if (!SetCallbacks(value))
                {
                    throw new System.ArgumentOutOfRangeException("Callbacks");
                }
            }
        }
    }
    /// <summary>
    /// Value type CallbacksRequest
    /// </summary>
    [global::System.Xml.Serialization.XmlType("CallbacksRequest")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NClassify.Generator", "1.0")]
    public partial class CallbacksRequest
    {
        private bool __has_page;
        private System.Int32 __page;
        protected bool SetPage(System.Int32 value)
        {
            __page = value;
            return __has_page = true;
        }
        public bool HasPage
        {
            get
            {
                return __has_page;
            }
            set
            {
                if (value) throw new System.ArgumentOutOfRangeException("HasPage");
                __has_page = false;
                __page = default(System.Int32);
            }
        }
        /// <summary>
        /// System.Int32 page
        /// </summary>
        public System.Int32 Page
        {
            get
            {
                return (__page);
            }
            set
            {
                if (!SetPage(value))
                {
                    throw new System.ArgumentOutOfRangeException("Page");
                }
            }
        }
        private bool __has_perPage;
        private System.Int32 __perPage;
        protected bool SetPerPage(System.Int32 value)
        {
            __perPage = value;
            return __has_perPage = true;
        }
        public bool HasPerPage
        {
            get
            {
                return __has_perPage;
            }
            set
            {
                if (value) throw new System.ArgumentOutOfRangeException("HasPerPage");
                __has_perPage = false;
                __perPage = default(System.Int32);
            }
        }
        /// <summary>
        /// System.Int32 per_page
        /// </summary>
        public System.Int32 PerPage
        {
            get
            {
                return (__perPage);
            }
            set
            {
                if (!SetPerPage(value))
                {
                    throw new System.ArgumentOutOfRangeException("PerPage");
                }
            }
        }
        private bool __has_event;
        private System.String __event;
        protected bool SetEvent(System.String value)
        {
            if (null == value) return false;
            __event = value;
            return __has_event = true;
        }
        public bool HasEvent
        {
            get
            {
                return __has_event;
            }
            set
            {
                if (value) throw new System.ArgumentOutOfRangeException("HasEvent");
                __has_event = false;
                __event = default(System.String);
            }
        }
        /// <summary>
        /// System.String event
        /// </summary>
        public NClassify.Generator.EventType Event
        {
            get
            {
                return new NClassify.Generator.EventType(__event);
            }
            set
            {
                if (!SetEvent(value.Value))
                {
                    throw new System.ArgumentOutOfRangeException("Event");
                }
            }
        }
        private bool __has_uri;
        private System.String __uri;
        protected bool SetUri(System.String value)
        {
            if (null == value) return false;
            __uri = value;
            return __has_uri = true;
        }
        public bool HasUri
        {
            get
            {
                return __has_uri;
            }
            set
            {
                if (value) throw new System.ArgumentOutOfRangeException("HasUri");
                __has_uri = false;
                __uri = default(System.String);
            }
        }
        /// <summary>
        /// System.String uri
        /// </summary>
        public System.String Uri
        {
            get
            {
                return (__uri);
            }
            set
            {
                if (!SetUri(value))
                {
                    throw new System.ArgumentOutOfRangeException("Uri");
                }
            }
        }
    }
    /// <summary>
    /// Value type CallbackIdentity
    /// </summary>
    [global::System.Xml.Serialization.XmlType("CallbackIdentity")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NClassify.Generator", "1.0")]
    public partial class CallbackIdentity
    {
        private bool __has_callbackId;
        private System.UInt64 __callbackId;
        [global::System.CLSCompliant(false)]
        protected bool SetCallbackId(System.UInt64 value)
        {
            __callbackId = value;
            return __has_callbackId = true;
        }
        public bool HasCallbackId
        {
            get
            {
                return __has_callbackId;
            }
            set
            {
                if (value) throw new System.ArgumentOutOfRangeException("HasCallbackId");
                __has_callbackId = false;
                __callbackId = default(System.UInt64);
            }
        }
        /// <summary>
        /// System.UInt64 callback_id
        /// </summary>
        [global::System.CLSCompliant(false)]
        public NClassify.Generator.CallbackId CallbackId
        {
            get
            {
                return new NClassify.Generator.CallbackId(__callbackId);
            }
            set
            {
                if (!SetCallbackId(value.Value))
                {
                    throw new System.ArgumentOutOfRangeException("CallbackId");
                }
            }
        }
    }
}
#endregion
